SET FOREIGN_KEY_CHECKS = 0;
TRUNCATE table attachment;
TRUNCATE table credentials;
TRUNCATE table credentials_email_address;
TRUNCATE table credentials_metadata;
TRUNCATE table email;
TRUNCATE table email_header;
TRUNCATE table email_header_value;
TRUNCATE table email_metadata;
TRUNCATE table email_recipient;
SET FOREIGN_KEY_CHECKS = 1;