logging:
  level:
    root: INFO

openapi:
  name: ${spring.application.name}
  title: ${spring.application.name}
  version: '@project.version@'

spring:
  application:
    name: api-email-reader
  datasource:
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
    driver-class-name: org.mariadb.jdbc.Driver
  security:
    oauth2:
      client:
        registration:
          messaging:
            authorization-grant-type: client_credentials
            provider: messaging
            client-id: ${integration.messaging.client-id}
            client-secret: ${integration.messaging.client-secret}
        provider:
          messaging:
            token-uri: ${integration.messaging.token-url}
  flyway:
    enabled: true
scheduled:
  shedlock-lock-at-most-for: PT2M
properties:
  credentials:
    secret-key: ${SECRET_KEY}

logbook:
  body-filters:
    jsonPath:
      - key: '$..content'
        value: '[base64]'
