spring:
  datasource:
    driver-class-name: ${DB_DRIVER}
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: ${HIBERNATE.DDL_AUTO}
jakarta:
  persistence:
    schema-generation:
      scripts:
        create-target: target/database/generated-schema.sql

properties:
  credentials:
    secret-key: ${SECRET_KEY}

scheduled:
  initial-delay: ${INITIAL_DELAY}
  fixed-rate: ${FIXED_RATE}
  email-age-check:
    initial-delay: ${CHECK_INITIAL_DELAY}
    fixed-rate: ${CHECK_FIXED_RATE}

integration:
  messaging:
    base-url: ${MESSAGING_BASE_URL}
    recipient-adress: ${MESSAGING_RECIPIENT_ADRESS}
    token-uri: ${MESSAGING_TOKEN_URI}
    client-id: ${MESSAGING_CLIENT_ID}
    client-secret: ${MESSAGING_CLIENT_SECRET}
