logging:
  level:
    root: INFO

openapi:
  name: ${spring.application.name}
  title: ${spring.application.name}
  version: '@project.version@'

spring:
  application:
    name: api-email-reader
  datasource:
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
    driver-class-name: org.mariadb.jdbc.Driver
  flyway:
    enabled: true
scheduled:
  check-for-new-emails:
    ews:
      name: ewsCheckForNewEmails
      cron: "-"
    graph:
      name: graphCheckForNewEmails
      cron: '*/10 * * * * *'
  check-for-old-emails:
    name: checkForOldEmails
    cron: "-"
  check-for-new-sms-emails:
    name: checkForNewSmsEmails
    cron: "-"
  shedlock-lock-at-most-for: PT2M
  maximum-execution-time: PT2M
properties:
  credentials:
    secret-key: ${SECRET_KEY}
logbook:
  body-filters:
    jsonPath:
      - key: '$..content'
        value: '[base64]'
